using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared._Crescent.Taxation;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Crescent.Taxation;

[GenerateTypedNameReferences]
public sealed partial class TaxationConsoleWindow : FancyWindow
{
    /// <summary>Raised with a fraction (0..1) when the operator sets the default rate.</summary>
    public event Action<float>? OnSetDefault;

    /// <summary>Raised with (protoId, fraction 0..1) when the operator sets a per-good override.</summary>
    public event Action<(string ProtoId, float Rate)>? OnSetOverride;

    /// <summary>Raised with a protoId when the operator clears a per-good override.</summary>
    public event Action<string>? OnClearOverride;

    private bool _canEdit;

    public TaxationConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("taxation-console-title");

        DefaultSetButton.OnPressed += _ =>
        {
            if (TryParsePercent(DefaultRateEdit.Text, out var rate))
                OnSetDefault?.Invoke(rate);
        };
    }

    public void UpdateState(TaxationConsoleState state)
    {
        _canEdit = state.CanEdit;

        TreasuryLabel.Text = Loc.GetString("taxation-console-treasury", ("balance", state.Treasury));
        AccessLabel.Text = Loc.GetString(state.CanEdit
            ? "taxation-console-access-granted"
            : "taxation-console-access-view");
        AccessLabel.Modulate = state.CanEdit ? Color.LightGreen : Color.Gray;

        DefaultRateEdit.Text = ToPercentString(state.DefaultRate);
        DefaultRateEdit.Editable = state.CanEdit;
        DefaultSetButton.Disabled = !state.CanEdit;

        GoodsContainer.RemoveAllChildren();

        foreach (var good in state.Goods)
            GoodsContainer.AddChild(BuildRow(good));
    }

    private Control BuildRow(TaxableGoodEntry good)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 1, 0, 1),
        };

        var name = new Label
        {
            Text = good.Name,
            HorizontalExpand = true,
            ClipText = true,
        };

        var price = new Label
        {
            Text = Loc.GetString("taxation-console-good-price", ("price", good.BasePrice)),
            MinWidth = 110,
        };

        var rateEdit = new LineEdit
        {
            Text = ToPercentString(good.EffectiveRate),
            MinWidth = 70,
            Editable = _canEdit,
            Margin = new Thickness(4, 0, 2, 0),
            ModulateSelfOverride = good.HasOverride ? Color.Gold : null,
        };

        var setButton = new Button
        {
            Text = Loc.GetString("taxation-console-set"),
            Disabled = !_canEdit,
        };
        setButton.OnPressed += _ =>
        {
            if (TryParsePercent(rateEdit.Text, out var rate))
                OnSetOverride?.Invoke((good.ProtoId, rate));
        };

        var clearButton = new Button
        {
            Text = Loc.GetString("taxation-console-clear"),
            Disabled = !_canEdit || !good.HasOverride,
            Margin = new Thickness(2, 0, 0, 0),
        };
        clearButton.OnPressed += _ => OnClearOverride?.Invoke(good.ProtoId);

        row.AddChild(name);
        row.AddChild(price);
        row.AddChild(new Label { Text = "%", VerticalAlignment = VAlignment.Center });
        row.AddChild(rateEdit);
        row.AddChild(setButton);
        row.AddChild(clearButton);
        return row;
    }

    private static string ToPercentString(float fraction)
    {
        return Math.Round(fraction * 100f).ToString(CultureInfo.InvariantCulture);
    }

    /// <summary>Parses a percent string (e.g. "25") into a fraction (0.25). Returns false if invalid.</summary>
    private static bool TryParsePercent(string? text, out float fraction)
    {
        fraction = 0f;
        if (string.IsNullOrWhiteSpace(text))
            return false;

        if (!float.TryParse(text.Trim().TrimEnd('%'), NumberStyles.Float, CultureInfo.InvariantCulture, out var pct))
            return false;

        fraction = Math.Clamp(pct / 100f, 0f, 1f);
        return true;
    }
}
