using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared._Crescent.Taxation;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Crescent.Taxation;

[GenerateTypedNameReferences]
public sealed partial class TreasuryConsoleWindow : FancyWindow
{
    /// <summary>Raised with the amount of credits to withdraw.</summary>
    public event Action<int>? OnWithdraw;

    private int _balance;

    public TreasuryConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("treasury-console-title");

        WithdrawButton.OnPressed += _ =>
        {
            if (int.TryParse(AmountEdit.Text?.Trim(), NumberStyles.Integer, CultureInfo.InvariantCulture, out var amount) && amount > 0)
                OnWithdraw?.Invoke(amount);
        };

        WithdrawAllButton.OnPressed += _ =>
        {
            if (_balance > 0)
                OnWithdraw?.Invoke(_balance);
        };
    }

    public void UpdateState(TreasuryConsoleState state)
    {
        _balance = state.Balance;

        BalanceLabel.Text = Loc.GetString("treasury-console-balance", ("balance", state.Balance));

        if (state.AlarmActive)
        {
            AlarmLabel.Text = Loc.GetString("treasury-console-alarm");
            AlarmLabel.Modulate = Color.Red;
        }
        else
        {
            AlarmLabel.Text = string.Empty;
        }

        StatusLabel.Text = Loc.GetString(state.Authorized
            ? "treasury-console-authorized"
            : "treasury-console-unauthorized");
        StatusLabel.Modulate = state.Authorized ? Color.LightGreen : Color.OrangeRed;

        AmountEdit.Editable = state.Authorized;
        WithdrawButton.Disabled = !state.Authorized;
        WithdrawAllButton.Disabled = !state.Authorized;
    }
}
