using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Crescent.Diplomacy;

/// <summary>
/// Standalone window for the diplomacy console. Hosts the panel the BUI owns; on a mainframe the
/// same panel is hosted in a tab instead.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DiplomacyConsoleMenu : DefaultWindow
{
    public DiplomacyConsoleMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetPanel(DiplomacyPanel panel)
    {
        PanelHost.AddChild(panel);
    }
}
