using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Crescent.Payment;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client._Crescent.Payment;

[GenerateTypedNameReferences]
public sealed partial class PaymentPanel : BoxContainer
{
    private static readonly Color RowBg = Color.FromHex("#1C1C22");
    private static readonly Color StaleBg = Color.FromHex("#2A2118");

    public event Action<NetUserId, int>? OnSetSalary;
    public event Action<NetUserId>? OnClearSalary;
    public event Action<NetUserId, int, string>? OnBonus;

    private PaymentBonusDialog? _bonusDialog;

    public PaymentPanel()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        // The dialog is its own window, so nothing else ties it to this panel's lifetime. Without
        // this it survives the console closing and fires its callback into a disposed BUI.
        if (disposing)
            CloseBonusDialog();
    }

    private void CloseBonusDialog()
    {
        _bonusDialog?.Close();
        _bonusDialog = null;
    }

    public void UpdateState(PaymentConsoleState state)
    {
        TreasuryLabel.Text = state.TreasuryBound
            ? Loc.GetString("payment-console-treasury-value", ("amount", state.Treasury))
            : Loc.GetString("payment-console-treasury-unbound");
        TreasuryLabel.FontColorOverride = state.TreasuryBound ? Color.LightGreen : Color.DarkOrange;

        // Total committed spend, so command can see the burn rate against the balance above.
        var perHour = state.Members.Sum(m => m.SalaryPerHour);
        PayrollLabel.Text = Loc.GetString("payment-console-payroll-total", ("amount", perHour));
        PayrollLabel.FontColorOverride = state.TreasuryBound && perHour > state.Treasury
            ? Color.DarkOrange
            : Color.DarkGray;

        MembersContainer.RemoveAllChildren();

        if (state.Members.Count == 0)
        {
            MembersContainer.AddChild(new Label
            {
                Text = Loc.GetString("payment-console-no-members"),
                FontColorOverride = Color.Gray,
                Margin = new Thickness(4, 2),
            });
            return;
        }

        foreach (var member in state.Members)
            MembersContainer.AddChild(BuildRow(member));
    }

    private Control BuildRow(PaymentMemberEntry member)
    {
        var row = new PanelContainer { MinHeight = 32 };
        row.PanelOverride = new StyleBoxFlat { BackgroundColor = member.Stale ? StaleBg : RowBg };

        var inner = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Margin = new Thickness(6, 4),
            HorizontalExpand = true,
            SeparationOverride = 4,
        };

        inner.AddChild(new Label
        {
            Text = member.Name,
            StyleClasses = { "ConsoleText" },
            // Greyed out when they're on the payroll but no longer in the faction, so command can prune.
            FontColorOverride = member.Stale ? Color.Gray : Color.White,
            HorizontalExpand = true,
            SizeFlagsStretchRatio = 2f,
            ClipText = true,
        });

        inner.AddChild(new Label
        {
            Text = member.Job,
            StyleClasses = { "ConsoleText" },
            FontColorOverride = Color.DarkGray,
            HorizontalExpand = true,
            SizeFlagsStretchRatio = 1.5f,
            ClipText = true,
        });

        inner.AddChild(new Label
        {
            Text = member.Stale
                ? Loc.GetString("payment-console-status-stale")
                : member.Payable
                    ? Loc.GetString("payment-console-status-payable")
                    : Loc.GetString("payment-console-status-unpayable"),
            StyleClasses = { "ConsoleText" },
            FontColorOverride = member.Payable ? Color.LightGreen : Color.DarkOrange,
            MinWidth = 90,
        });

        var salaryEdit = new LineEdit
        {
            Text = member.SalaryPerHour.ToString(),
            MinWidth = 90,
            PlaceHolder = Loc.GetString("payment-console-salary-placeholder"),
        };
        inner.AddChild(salaryEdit);

        var user = member.User;

        // Joined into one control strip so the three actions read as a single unit per member.
        var setButton = new MonotoneButton
        {
            Text = Loc.GetString("payment-console-set-button"),
            Shape = MonotoneButtonShape.OpenRight,
            MinWidth = 70,
        };
        setButton.OnPressed += _ =>
        {
            if (!int.TryParse(salaryEdit.Text, out var salary) || salary < 0)
                return;

            // Mirror the server-side cap here so an over-limit entry snaps back visibly instead of
            // being silently trimmed after the round-trip.
            salary = Math.Min(salary, PaymentConsole.MaxSalaryPerHour);
            salaryEdit.Text = salary.ToString();

            OnSetSalary?.Invoke(user, salary);
        };
        inner.AddChild(setButton);

        var clearButton = new MonotoneButton
        {
            Text = Loc.GetString("payment-console-clear-button"),
            Shape = MonotoneButtonShape.OpenBoth,
            MinWidth = 70,
            Disabled = member.SalaryPerHour <= 0,
        };
        clearButton.OnPressed += _ => OnClearSalary?.Invoke(user);
        inner.AddChild(clearButton);

        var bonusButton = new MonotoneButton
        {
            Text = Loc.GetString("payment-console-bonus-button"),
            Shape = MonotoneButtonShape.OpenLeft,
            MinWidth = 70,
            Disabled = !member.Payable,
        };
        bonusButton.OnPressed += _ => OpenBonusDialog(member);
        inner.AddChild(bonusButton);

        row.AddChild(inner);
        return row;
    }

    private void OpenBonusDialog(PaymentMemberEntry member)
    {
        // Only one at a time, so an earlier dialog can't be left behind pointing at another member.
        CloseBonusDialog();

        var dialog = new PaymentBonusDialog(member.Name);
        var user = member.User;

        dialog.OnConfirmed += (amount, reason) => OnBonus?.Invoke(user, amount, reason);
        dialog.OnClose += () =>
        {
            if (_bonusDialog == dialog)
                _bonusDialog = null;
        };

        _bonusDialog = dialog;
        dialog.OpenCentered();
    }
}
