using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Crescent.Payment;

/// <summary>
/// Standalone window for the payroll console. Hosts the panel the BUI owns; on a mainframe the same
/// panel is hosted in a tab instead.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PaymentConsoleWindow : DefaultWindow
{
    public PaymentConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetPanel(PaymentPanel panel)
    {
        PanelHost.AddChild(panel);
    }
}
