using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Crescent.AlertConsole;

/// <summary>
/// Standalone window for the alert console. Hosts the panel the BUI owns; on a mainframe the same
/// panel is hosted in a tab instead.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AlertConsoleMenu : DefaultWindow
{
    public AlertConsoleMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetPanel(AlertPanel panel)
    {
        PanelHost.AddChild(panel);
    }
}
