using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Crescent.Overwatch;

/// <summary>
/// Standalone window for the overwatch console. Hosts the panel the BUI owns; on a mainframe the
/// same panel is hosted in a tab instead.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OverwatchWindow : FancyWindow
{
    public OverwatchWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetPanel(OverwatchPanel panel)
    {
        PanelHost.AddChild(panel);
    }
}
