using System.Linq;
using Content.Client.GameTicking.Managers;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Crescent.Mainframe;

/// <summary>
/// Shell window that hosts each console's panel as a tab.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MainframeWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    private readonly ClientGameTicker _gameTicker;
    private readonly Dictionary<MainframeTab, BoxContainer> _slots = new();

    public MainframeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _gameTicker = _sysMan.GetEntitySystem<ClientGameTicker>();

        // Every slot is created up front, in ordinal order, so a tab always lands in the same
        // position no matter which sub-BUI attaches first. Slots stay hidden until filled.
        foreach (var tab in Enum.GetValues<MainframeTab>())
        {
            var slot = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalExpand = true,
            };

            Tabs.AddChild(slot);
            TabContainer.SetTabTitle(slot, Loc.GetString($"mainframe-tab-{tab.ToString().ToLowerInvariant()}"));
            TabContainer.SetTabVisible(slot, false);
            _slots[tab] = slot;
        }

        UpdateFooter();
    }

    /// <summary>Names the machine after the console entity, so each faction's mainframe identifies itself.</summary>
    public void SetMachineName(string name)
    {
        Title = name;
        MastheadLabel.Text = name.ToUpperInvariant();
    }

    public void SetTab(MainframeTab tab, Control panel)
    {
        var slot = _slots[tab];
        slot.RemoveAllChildren();
        slot.AddChild(panel);
        TabContainer.SetTabVisible(slot, true);
        UpdateFooter();
    }

    public void ClearTab(MainframeTab tab)
    {
        if (!_slots.TryGetValue(tab, out var slot))
            return;

        slot.RemoveAllChildren();
        TabContainer.SetTabVisible(slot, false);
        UpdateFooter();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // Shift duration, matching what the PDA shows — CurTime alone is server uptime, which would
        // read as a wrong clock.
        var time = _timing.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
        var clock = $"{time.Hours:D2}:{time.Minutes:D2}:{time.Seconds:D2}";

        // Only touch the label when the text actually changes (once a second) — setting it every
        // frame invalidates the shared window's layout for nothing.
        if (ClockLabel.Text != clock)
            ClockLabel.Text = clock;
    }

    private void UpdateFooter()
    {
        var linked = _slots.Count(kv => kv.Value.Parent != null && TabContainer.GetTabVisible(kv.Value));

        StatusLabel.Text = Loc.GetString("mainframe-status-online");
        LinkLabel.Text = Loc.GetString("mainframe-status-modules", ("count", linked), ("total", _slots.Count));
    }
}
