using Content.Client.Shuttles.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Crescent.DroneControl;
using Content.Shared.Shuttles.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Timing;
using System.Linq;
using System.Numerics;

namespace Content.Client._Crescent.DroneControl;

[GenerateTypedNameReferences]
public sealed partial class DroneConsoleWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IMapManager _mapManager = default!;
    private readonly SharedShuttleSystem _shuttles;
    private readonly SharedTransformSystem _xform;

    public ShuttleNavControl Radar => NavRadar;
    public Action<EntityCoordinates>? OnMoveOrder;
    public Action<EntityCoordinates>? OnAttackOrder;

    public Action? OnDeploy;
    public Action<DroneStance>? OnSetStance;
    public Action<DroneTargeting>? OnSetTargeting;
    public Action<DroneFormation>? OnSetFormation;
    public Action<string>? OnSpawn;

    public HashSet<NetEntity> SelectedDrones = new();

    private readonly Dictionary<NetEntity, Button> _droneButtons = new();
    private readonly List<string> _spawnableDrones = new();

    public DroneConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _shuttles = _entity.System<SharedShuttleSystem>();
        _xform = _entity.System<SharedTransformSystem>();

        NavRadar.OnRadarClick += OnRadarClick;

        SelectAllBtn.OnPressed += _ =>
        {
            foreach (var key in _droneButtons.Keys)
                SelectedDrones.Add(key);

            RefreshButtonVisuals();
        };

        DeselectAllBtn.OnPressed += _ =>
        {
            SelectedDrones.Clear();
            RefreshButtonVisuals();
        };

        DeployBtn.OnPressed += _ => OnDeploy?.Invoke();

        StanceAttackBtn.OnPressed += _ => OnSetStance?.Invoke(DroneStance.Attack);
        StanceDefendBtn.OnPressed += _ => OnSetStance?.Invoke(DroneStance.Defend);
        StanceFollowBtn.OnPressed += _ => OnSetStance?.Invoke(DroneStance.Follow);

        TargetEnemiesBtn.OnPressed += _ => OnSetTargeting?.Invoke(DroneTargeting.Enemies);
        TargetAllBtn.OnPressed += _ => OnSetTargeting?.Invoke(DroneTargeting.All);

        foreach (var formation in Enum.GetValues<DroneFormation>())
            FormationOption.AddItem(formation.ToString(), (int) formation);

        FormationOption.OnItemSelected += args =>
        {
            FormationOption.SelectId(args.Id);
            OnSetFormation?.Invoke((DroneFormation) args.Id);
        };

        SpawnOption.OnItemSelected += args => SpawnOption.SelectId(args.Id);

        ProduceBtn.OnPressed += _ =>
        {
            var id = SpawnOption.SelectedId;
            if (id >= 0 && id < _spawnableDrones.Count)
                OnSpawn?.Invoke(_spawnableDrones[id]);
        };
    }

    private void OnRadarClick(EntityCoordinates coord)
    {
        if (!_timing.IsFirstTimePredicted)
            return;

        var worldCoord = _xform.ToMapCoordinates(coord);
        var mapId = worldCoord.MapId;

        var box = Box2.CenteredAround(worldCoord.Position, new Vector2(2f, 2f));
        EntityUid? foundGrid = null;
        _mapManager.FindGridsIntersecting(mapId, box, (uid, _) =>
        {
            foundGrid = uid;
            return false; // stop when we find one
        }, false, false);

        if (foundGrid != null)
            OnAttackOrder?.Invoke(_xform.ToCoordinates(foundGrid.Value, worldCoord));
        else
            OnMoveOrder?.Invoke(_xform.ToCoordinates(worldCoord));
    }

    public void UpdateState(DroneConsoleBoundUserInterfaceState state)
    {
        NavRadar.UpdateState(state.NavState);
        NavRadar.UpdateState(state.IFFState);

        CarrierPanel.Visible = state.IsCarrier;
        if (state.IsCarrier)
        {
            DeployedLabel.Text = $"Drones: {state.DeployedCount}/{state.MaxDrones}";

            StanceAttackBtn.Pressed = state.Stance == DroneStance.Attack;
            StanceDefendBtn.Pressed = state.Stance == DroneStance.Defend;
            StanceFollowBtn.Pressed = state.Stance == DroneStance.Follow;

            TargetEnemiesBtn.Pressed = state.Targeting == DroneTargeting.Enemies;
            TargetAllBtn.Pressed = state.Targeting == DroneTargeting.All;

            FormationOption.SelectId((int) state.Formation);

            // Rebuild the production dropdown only when the available list actually changes.
            if (!_spawnableDrones.SequenceEqual(state.SpawnableDrones))
            {
                _spawnableDrones.Clear();
                _spawnableDrones.AddRange(state.SpawnableDrones);

                SpawnOption.Clear();
                for (var i = 0; i < _spawnableDrones.Count; i++)
                    SpawnOption.AddItem(_spawnableDrones[i], i);

                if (_spawnableDrones.Count > 0)
                    SpawnOption.SelectId(0);
            }

            SpawnRow.Visible = _spawnableDrones.Count > 0;
        }

        // return if we already have all drones linked
        var match = 0;
        foreach (var (netEnt, _) in state.LinkedDrones)
            match += _droneButtons.ContainsKey(netEnt) ? 1 : 0;

        if (match == state.LinkedDrones.Count && match == _droneButtons.Count)
            return;

        DroneListContainer.DisposeAllChildren();
        _droneButtons.Clear();

        foreach (var (netEnt, gridEnt) in state.LinkedDrones)
        {
            var label = _shuttles.GetIFFLabel(_entity.GetEntity(gridEnt), self: false);
            var btn = new Button
            {
                Text = label,
                ToggleMode = true,
                Pressed = SelectedDrones.Contains(netEnt)
            };

            btn.OnPressed += (args) =>
            {
                if (btn.Pressed) SelectedDrones.Add(netEnt);
                else SelectedDrones.Remove(netEnt);
            };

            _droneButtons[netEnt] = btn;
            DroneListContainer.AddChild(btn);
        }
    }

    private void RefreshButtonVisuals()
    {
        foreach (var (netEnt, btn) in _droneButtons)
        {
            btn.Pressed = SelectedDrones.Contains(netEnt);
        }
    }
}
