using System.Linq;
using Content.Shared._Crescent.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Crescent.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class GamblingUiFragment : LayoutContainer
{
    private static readonly TimeSpan ToastDuration = TimeSpan.FromSeconds(4);

    private static readonly StyleBoxFlat ToastGoodStyle = MakeToastStyle("#1f3327", "#54a068");
    private static readonly StyleBoxFlat ToastBadStyle = MakeToastStyle("#3a1f22", "#c84a50");

    // Kept parallel with the OptionButton item order so the selected id maps back to a bet kind.
    private static readonly RouletteBetKind[] BetKinds =
    {
        RouletteBetKind.Red,
        RouletteBetKind.Black,
        RouletteBetKind.Odd,
        RouletteBetKind.Even,
        RouletteBetKind.Low,
        RouletteBetKind.High,
        RouletteBetKind.Dozen1,
        RouletteBetKind.Dozen2,
        RouletteBetKind.Dozen3,
        RouletteBetKind.Straight,
    };

    private int _toastGeneration;

    public event Action<int>? OnSpinSlots;
    public event Action<RouletteBetKind, int, int>? OnRouletteBet;
    public event Action<BlackjackAction, int>? OnBlackjack;

    public GamblingUiFragment()
    {
        RobustXamlLoader.Load(this);

        LayoutContainer.SetAnchorPreset(BackgroundPanel, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(MainColumn, LayoutContainer.LayoutPreset.Wide);

        Tabs.SetTabTitle(0, Loc.GetString("gambling-ui-tab-slots"));
        Tabs.SetTabTitle(1, Loc.GetString("gambling-ui-tab-roulette"));
        Tabs.SetTabTitle(2, Loc.GetString("gambling-ui-tab-blackjack"));

        var winPercent = (int) MathF.Round(GamblingTables.WinProfit * 100);
        SlotPaytableLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("gambling-ui-slots-info", ("percent", winPercent))));
        RouletteInfoLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("gambling-ui-roulette-info", ("percent", winPercent))));
        BlackjackRulesLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("gambling-ui-blackjack-rules", ("percent", winPercent))));

        for (var i = 0; i < BetKinds.Length; i++)
            BetKindOption.AddItem(Loc.GetString($"gambling-roulette-bet-{BetKinds[i].ToString().ToLowerInvariant()}"), i);

        BetKindOption.SelectId(0);

        BetKindOption.OnItemSelected += args =>
        {
            BetKindOption.SelectId(args.Id);
            StraightNumberEdit.Visible = BetKinds[args.Id] == RouletteBetKind.Straight;
        };

        SpinButton.OnPressed += _ =>
        {
            if (TryReadBet(SlotBetEdit, out var bet))
                OnSpinSlots?.Invoke(bet);
        };

        RouletteButton.OnPressed += _ =>
        {
            if (!TryReadBet(RouletteBetEdit, out var bet))
                return;

            var kind = BetKinds[BetKindOption.SelectedId];
            var number = 0;
            if (kind == RouletteBetKind.Straight && !int.TryParse(StraightNumberEdit.Text?.Trim(), out number))
            {
                ShowToast(Loc.GetString("gambling-error-number"), false);
                return;
            }

            OnRouletteBet?.Invoke(kind, number, bet);
        };

        DealButton.OnPressed += _ =>
        {
            if (TryReadBet(BlackjackBetEdit, out var bet))
                OnBlackjack?.Invoke(BlackjackAction.Deal, bet);
        };

        HitButton.OnPressed += _ => OnBlackjack?.Invoke(BlackjackAction.Hit, 0);
        StandButton.OnPressed += _ => OnBlackjack?.Invoke(BlackjackAction.Stand, 0);

        RenderBlackjack(false, Array.Empty<GamblingCard>(), Array.Empty<GamblingCard>(), false);
    }

    public void UpdateState(GamblingUiState state)
    {
        BalanceLabel.Text = Loc.GetString("gambling-ui-balance", ("balance", state.Balance));

        if (state.Error is { } err)
            ShowToast(err, false);
        else if (state.Toast is { } toast)
            ShowToast(toast, state.ToastGood);

        RenderReels(state.Reels);
        RenderPocket(state.LastPocket);
        RenderBlackjack(state.HandActive, state.PlayerCards, state.DealerCards, state.DealerHoleHidden);
    }

    #region Slots

    private void RenderReels(SlotSymbol[]? reels)
    {
        if (reels is not { Length: 3 })
        {
            ReelsLabel.Text = Loc.GetString("gambling-ui-slots-idle");
            return;
        }

        ReelsLabel.Text = string.Join("  |  ", reels.Select(SymbolGlyph));
    }

    // Uses glyphs present in the default NotoSans font stack. Colour emoji (🍒, 💎, …) are
    // not in that stack and render as tofu/"?", so the reels must stick to plain unicode.
    private static string SymbolGlyph(SlotSymbol symbol) => symbol switch
    {
        SlotSymbol.Cherry => "♥",
        SlotSymbol.Lemon => "●",
        SlotSymbol.Bell => "♪",
        SlotSymbol.Star => "★",
        SlotSymbol.Diamond => "♦",
        SlotSymbol.Seven => "7",
        _ => "?",
    };

    #endregion

    #region Roulette

    private void RenderPocket(int pocket)
    {
        if (pocket < 0)
        {
            PocketLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("gambling-ui-roulette-idle")));
            return;
        }

        var color = PocketColorHex(pocket);
        var text = Loc.GetString("gambling-ui-roulette-pocket", ("pocket", GamblingTables.PocketLabel(pocket)));
        PocketLabel.SetMessage(FormattedMessage.FromMarkupOrThrow($"[color={color}][bold]{text}[/bold][/color]"));
    }

    private static string PocketColorHex(int pocket)
    {
        if (GamblingTables.IsGreen(pocket))
            return "#3fae5a";

        return GamblingTables.IsRed(GamblingTables.PocketNumber(pocket)) ? "#d64545" : "#cccccc";
    }

    #endregion

    #region Blackjack

    private void RenderBlackjack(bool handActive, IReadOnlyList<GamblingCard> player, IReadOnlyList<GamblingCard> dealer, bool holeHidden)
    {
        HitButton.Disabled = !handActive;
        StandButton.Disabled = !handActive;

        if (player.Count == 0)
        {
            DealerLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("gambling-ui-blackjack-idle")));
            PlayerLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(string.Empty));
            return;
        }

        // With the hole card hidden the visible dealer total would be misleading, so we hide it.
        var dealerTotalText = holeHidden ? "?" : GamblingTables.HandTotal(dealer).Total.ToString();
        var dealerCardsText = CardsMarkup(dealer);
        if (holeHidden)
            dealerCardsText += "  [color=#888888]??[/color]";

        DealerLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("gambling-ui-blackjack-dealer",
            ("cards", dealerCardsText),
            ("total", dealerTotalText))));

        PlayerLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("gambling-ui-blackjack-player",
            ("cards", CardsMarkup(player)),
            ("total", GamblingTables.HandTotal(player).Total))));
    }

    private static string CardsMarkup(IReadOnlyList<GamblingCard> cards)
    {
        return string.Join("  ", cards.Select(c =>
        {
            var color = GamblingTables.SuitIsRed(c.Suit) ? "#d64545" : "#dddddd";
            return $"[color={color}]{GamblingTables.CardLabel(c)}[/color]";
        }));
    }

    #endregion

    #region Shared

    private bool TryReadBet(LineEdit edit, out int bet)
    {
        if (!int.TryParse(edit.Text?.Trim(), out bet) || bet <= 0)
        {
            bet = 0;
            ShowToast(Loc.GetString("gambling-error-bet-invalid"), false);
            return false;
        }

        return true;
    }

    private void ShowToast(string message, bool good)
    {
        _toastGeneration++;
        var gen = _toastGeneration;

        ToastLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(message));
        ToastStrip.PanelOverride = good ? ToastGoodStyle : ToastBadStyle;
        ToastStrip.Visible = true;

        Robust.Shared.Timing.Timer.Spawn(ToastDuration, () =>
        {
            if (gen == _toastGeneration)
                ToastStrip.Visible = false;
        });
    }

    private static StyleBoxFlat MakeToastStyle(string bg, string border) => new()
    {
        BackgroundColor = Color.FromHex(bg),
        BorderThickness = new Thickness(2),
        BorderColor = Color.FromHex(border),
        ContentMarginLeftOverride = 10,
        ContentMarginRightOverride = 10,
        ContentMarginTopOverride = 6,
        ContentMarginBottomOverride = 6,
    };

    #endregion
}
